### ISSUE TITLE
java.lang.IllegalStateException: Can't access the Fragment View's LifecycleOwner when getView()

### ISSUE THREAD

**Issue by nguyenlinhnttu** [Zhuinden/fragmentviewbindingdelegate-kt#9]
java.lang.IllegalStateException: Can't access the Fragment View's LifecycleOwner when getView() is null i.e., before onCreateView() or after onDestroyView()
        at androidx.fragment.app.Fragment.getViewLifecycleOwner(Fragment.java:361)
        at com.base.android.common.extentions.FragmentViewBindingDelegate.getValue(FragmentViewBindingDelegate.kt:42)
        at com.base.android.feature.HomeFragment.getBinding(Unknown Source:10)
        at com.base.android.feature.HomeFragment.nextBanner(HomeFragment.kt:173)
        at com.base.android.feature.HomeFragment.access$nextBanner(HomeFragment.kt:27)
        at com.base.android.feature.HomeFragment$repeatBannerTask$1.invokeSuspend(HomeFragment.kt:167)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:227)
        at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:166)
        at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:362)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:396)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:388)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeUndispatched(CancellableContinuationImpl.kt:484)
        at kotlinx.coroutines.android.HandlerContext$scheduleResumeAfterDelay$$inlined$Runnable$1.run(Runnable.kt:19)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)

**Comment by Zhuinden** [comment]
The bug is in your code, you should be correctly managing the coroutine's lifecycle using `viewLifecycleOwner.lifecycleScope.launchWhenStarted {`
